In [2]:
import numpy as np

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
print(type(a)," and ",type(a[0]))

<class 'numpy.ndarray'>  and  <class 'numpy.float64'>


**slicing from 2d array**

In [5]:
b=np.random.randint(100,size=(5,5))
b

array([[86, 58, 77, 46, 59],
       [16, 31, 13, 87, 51],
       [46, 91, 24, 83, 79],
       [88, 14, 45, 99, 13],
       [70,  6,  2, 44, 36]])

In [8]:
b[2:4]

array([[46, 91, 24, 83, 79],
       [88, 14, 45, 99, 13]])

In [10]:
b[0:4,1:3]

array([[58, 77],
       [31, 13],
       [91, 24],
       [14, 45]])

In [11]:
b=np.ones((2,3,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

**slicing from 3d array**

In [12]:
d=np.random.randint(100,size=(2,5,5))
d

array([[[41, 75,  1, 82,  3],
        [52, 95, 90, 58, 12],
        [27, 47, 18, 10, 39],
        [70, 64, 19, 81, 51],
        [63, 64, 34, 94, 65]],

       [[73, 57, 35, 80, 22],
        [11,  5, 58, 51, 77],
        [ 1, 62, 99, 61, 43],
        [80, 26, 51, 37, 15],
        [23, 78, 12, 51, 87]]])

In [13]:
d[1:2,1:4,2:4]

array([[[58, 51],
        [99, 61],
        [51, 37]]])